export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";
export const POST_LOADING = "POST_LOADING";
